# This workflow will do a clean installation of node dependencies, cache/restore them, and build the source code
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 23
      uses: actions/setup-node@v4
      with:
        node-version: '23.x'
        cache: 'npm'
        
    - run: npm run build
